name: sumo312
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.2
  - prompt-toolkit=3.0.47
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.0
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - pip:
      - attrs==24.2.0
      - branca==0.7.2
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - fiona==1.10.0
      - folium==0.17.0
      - fonttools==4.53.1
      - geopandas==0.14.4
      - idna==3.8
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - networkx==3.3
      - numpy==1.26.4
      - osmnx==1.9.4
      - pandas==2.2.2
      - pillow==10.4.0
      - pyparsing==3.1.4
      - pyproj==3.6.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.32.3
      - scipy==1.14.1
      - seaborn==0.13.2
      - shapely==2.0.6
      - sumolib==1.20.0
      - tqdm==4.66.5
      - traci==1.20.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - xyzservices==2024.9.0
